
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXlNREV4TkRJd01sb1hEVE16TURNeE56RXhOREl3TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjkrCnJMYjk1WS81UUdFWklwVm5iOHFnQjJZTjlJZDZxK085RTQwWVFYNVQ0a0pQOU5zNHpqSkl4M3Z2TFFmKzQxQ2wKOUpwTmJBUElsVWFyTC9YejFiTFZMQ1c1dTBNcnBGVk5UUTM2ZlgyM09zeDY3M0FtZzVqYW1OWlRWbDlkSkZwNApMZnc5QVp3bDdkNFhBbUc5Q1JLMHJPd3N3My9JU1lrN3dOT2RkUUhXS3M0aHlVKzdFZHdxWlVLeUZDS043UkhpCkUvcWhhVzdiNjBKbVY2SG50RGRpYktJK0N5Kytqc1JCNm4xVGpYTVduZHFRSTczMzVXY2N1YXNqU0FmSElKU3AKeW9ZenhwdXpCVTZieDlaZFRWaDhJaE5lcU1LQmtRM3ZKMXV1MnFsSmxXcEp5cGw1cEJQc2JtTk5jeE1oODB2SwpScHZkaGthS0hRcXYyZ0IrY3hzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBcnk0VXRaRm1uZitIUDVWNlJHcnN6SjcrbWZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSDlHc0pHcnFjKytrYXQwWEpqcwpQTHkrTmlkQ2M5UHdHbTdodHZFZ21kMHZ0dm91VnRHbzNDMGVqYjlFc081UlhzSURBQzFCOGZybHQyemdnYW55CjM5clN3dG5MQXR5akxQajZ1RU1lQkxWOU5McXpHdkhkSUZBaWVPZ3pBcHh1b2FrRWJCNUgxWE1sWWhFUHFjWDEKSDRaMmtHRVBFYWJRMUpXYmU3VFRpQk52Q1NDMFBpbUI3ZFUzWUN3eklnTnlKWGxnb0FlUXlaQ3kxMEhLVDRBcgpDQ29iMTVab0VZaitOQmJqaGhMWnpOQmNmYmV2QXFzbjNYcmVDSnRQc3ZZNUdoc3MvcE9tU2RJUDJVR0tKSEFQClByV3ZUcWYzdGVRbDVGZ1JGcloramZ3bFlVRFh0ajNWWGZpcUxxM21KeHBjeGludHQyVXlQRk5zblN1VVh5S2sKNHVnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://2325698c-7061-4c8c-9239-4fc8c0d588ef.eu-central-2.linodelke.net:443
  name: lke98699

users:
- name: lke98699-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2RUcyMUZZZy1TSnUxXzVpenhBc3ByVFlMUHVNSmhaU3FSaFdJVk1UeWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcG54bWgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTVhNjIyY2YtMWIxZC00OTU5LWE5MTEtZTc1Y2U1NGU4ZDgwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.RzQEhIxMNay4DPpJSXL2UBABa0bh6rJOLY3sOvvBdbGeyemkT3DHahauusm5RPaHEYhsbS79jQUF8d-ZFwJwZqCHylREW5xFI4gWg5ROaiA6jeue5JBGUr7DHMrvrErzNFKGLMQHvdpKZj0uvlgCohD6SSiwTrwfF07fkXfayhzAFXdvFBQmOsssYVVjVEVgeeURRu7n87Dz6J2s89BIQlolWoNuK-hMym9WbJoc5EcUsDDZRAO-l7TT5RHGnh7GyzLYnup2M1bcOduSJTSX34SQJA3ZajK0U5z90mVqCIuS2j4flx0l2GNPISSpY-DWES9Iy8XDmKESE_jerfS78Q

contexts:
- context:
    cluster: lke98699
    namespace: default
    user: lke98699-admin
  name: lke98699-ctx

current-context: lke98699-ctx
